project:
  type: book

book:
  #title: "Longitudinal Analysis with the ABCD Study Data"
  author: "Biostatistics Working Group of the ABCD Study"
  chapters:
    - index.qmd
    - part: "**Manuscript**"
      chapters:
        - manuscript_working_draft.qmd
    - part: data_wrangling.qmd
      chapters:
        - data_wrangling.qmd
    - part: paired_samples_t-test_main.qmd
      chapters:
        - paired_samples_t-test_main_example_1.qmd
    - part: repeated_measures_anova_main.qmd
      chapters:
        - repeated_measures_anova_main_example_1.qmd
        #- rnova_single_group_design.qmd
        #- rnova_multiple_group_design.qmd
    - part: difference_scores_main.qmd
      chapters:
        - difference_scores_one_sample_ttest.qmd
        - difference_scores_paired_samples_ttest.qmd
        - difference_scores_simple_regression.qmd
    - part: change_scores_main.qmd
      chapters:
        - change_scores_ancova.qmd
        - change_scores_multiple_regression.qmd
    - part: lmm_main.qmd
      chapters:
        - lmm_intercept_only.qmd
        - lmm_intercept_and_slope.qmd
    - part: signed_ranksum_test_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: marginal_models_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: generalized_estimating_equations_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: generalized_linear_mixed_models_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: autoregressive_cross-lagged_panel_models_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: latent_change_scores_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: latent_growth_curves_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: multivariate_latent_growth_curves_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: latent_transition_analysis_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: growth_mixture_modeling_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: latent_statetrait_models_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: random_intercept_cross-lagged_panel_models_main.qmd
      chapters:
        - data_wrangling.qmd
    - part: latent_curve_model_with_structured_residuals_main.qmd
      chapters:
        - data_wrangling.qmd
      #chapters:
      #- difference_scores_one_sample_ttest.qmd
      #- difference_scores_paired_samples_ttest.qmd
      #- difference_scores_simple_regression.qmd
      #- change_scores_ancova.qmd
      #- change_scores_multiple_regression.qmd
      #- lmm_intercept_only.qmd
      #- lmm_intercept_and_slope.qmd
    - part: "TBD"
      chapters:
        - tbd.qmd
        #- longitudinal_twin_analysis
        #- longitudinal_stability_analysis
        #- psychometrics
        #- missing data
        - references.qmd
  appendices:
    - resources.qmd
  page-navigation: true
  #repo-url: https://github.com/
  #repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  navbar:
    search: true
    title: Longitudinal Analysis using ABCD Study data
    pinned: true
    collapsed: true
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
        #text: blip
  page-footer:
    center:
      - text: "About"
        href: resources.qmd
      - text: "xxxxx"
        href: resources.qmd
      - text: "xxxxxx"
        href: resources.qmd
  #cover-image: cover.png
  #abstract

comments:
  hypothesis: true

bibliography: references.bib
#csl: citestyle.csl

format:
  html:
    theme: cosmo
    code-copy: true
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
