project:
  type: book

book:
  #title: "Longitudinal Analysis with the ABCD Study Data"
  author: "Biostatistics Working Group of the ABCD Study"
  chapters:
    - index.qmd
    - part: "Manuscript"
      chapters:
        - manuscript_working_draft.qmd
    - part: dataWrangling/data_wrangling.qmd
      chapters:
        - example1_blank.qmd
    - part: differenceScores/difference_scores_main.qmd
      chapters:
        - differenceScores/difference_scores_one_sample_ttest.qmd
        - differenceScores/difference_scores_one_sample_ttestr.qmd
        - differenceScores/difference_scores_paired_samples_ttest.qmd
        - differenceScores/difference_scores_simple_regression.qmd
    - part: changeScores/change_scores_main.qmd
      chapters:
        - changeScores/change_scores_ancova.qmd
        - changeScores/change_scores_multiple_regression.qmd
    - part: linearMixedModels/lmm_main.qmd
      chapters:
        - linearMixedModels/lmm_intercept_only.qmd
      #- linearMixedModels/lmm_intercept_and_slope.qmd
    - part: signedRankSumTest/signed_ranksum_test_main.qmd
      chapters:
        - example1_blank.qmd
    - part: marginalModels/marginal_models_main.qmd
      chapters:
        - example1_blank.qmd
    - part: generalizedEstimatingEquations/generalized_estimating_equations_main.qmd
      chapters:
        - example1_blank.qmd
    - part: generalizedLinearMixedModels/generalized_linear_mixed_models_main.qmd
      chapters:
        - example1_blank.qmd
    - part: autoregressiveCLPM/autoregressive_cross-lagged_panel_models_main.qmd
      chapters:
        - example1_blank.qmd
    - part: latentChangeScores/latent_change_scores_main.qmd
      chapters:
        - example1_blank.qmd
    - part: latentGrowthCurves/latent_growth_curves_main.qmd
      chapters:
        - example1_blank.qmd
    - part: multivariateLatentGrowthCurve/multivariate_latent_growth_curves_main.qmd
      chapters:
        - example1_blank.qmd
    - part: latentTransitionAnalysis/latent_transition_analysis_main.qmd
      chapters:
        - example1_blank.qmd
    - part: growthMixtureModels/growth_mixture_modeling_main.qmd
      chapters:
        - example1_blank.qmd
    - part: latentStateTraitModels/latent_statetrait_models_main.qmd
      chapters:
        - example1_blank.qmd
    - part: randomInterceptCLPM/random_intercept_cross-lagged_panel_models_main.qmd
      chapters:
        - example1_blank.qmd
    - part: latentCurveModelStructuredResiduals/latent_curve_model_with_structured_residuals_main.qmd
      chapters:
        - example1_blank.qmd
      #chapters:
      #- difference_scores_one_sample_ttest.qmd
      #- difference_scores_paired_samples_ttest.qmd
      #- difference_scores_simple_regression.qmd
      #- change_scores_ancova.qmd
      #- change_scores_multiple_regression.qmd
      #- lmm_intercept_only.qmd
      #- lmm_intercept_and_slope.qmd
    - part: "TBD"
      chapters:
        - tbd.qmd
        #- longitudinal_twin_analysis
        #- longitudinal_stability_analysis
        #- psychometrics
        #- missing data
        - references.qmd
  appendices:
    - resources.qmd
  page-navigation: true
  #repo-url: https://github.com/
  #repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  navbar:
    search: true
    title: Longitudinal Analysis using ABCD Study data
    pinned: true
    collapsed: true
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
        #text: blip
  page-footer:
    center:
      - text: "About"
        href: resources.qmd
      - text: "xxxxx"
        href: resources.qmd
      - text: "xxxxxx"
        href: resources.qmd
  #cover-image: cover.png
  #abstract

comments:
  hypothesis: true

bibliography: references.bib
#csl: citestyle.csl

format:
  html:
    theme: cosmo
    code-copy: true
    number-sections: true
    number-depth: 4
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex
