# Growth Mixture Modeling {.unnumbered}

#### Growth mixture models (GMM)

Example 2. Growth Mixture Modeling (GMM) On some occasions the conventional LGM may be limited in that it describes all individuals as coming from the same population, not accounting for potentially important subgroup effects. An important extension of the conventional model, GMM allows different unobserved subgroups to follow distinct trajectories. By allowing the intercept and slope growth factors to vary across groups, the GMM approach estimates a distinct group-mean trajectory with its own unique variance, for each latent class. A special case of GMM, LCGA models a separate trajectory for each latent class, but the growth factor variances [Clearer to say intercept and slope variances rather than growth factor?] within each class are fixed to zero (i.e., assumes homogenous within-class patterns of growth). As this approach is less computationally expensive, it is often a useful starting approach for identifying different underlying trajectories prior conducting a GMM. Expanding on our prior example, we now examine a GMM using the same BPM Externalizing scale scores used in the conventional model. A successive number of latent classes were specified across models and the optimal number of classes were determined by investigating recommended model selection criteria (e.g., adjusted Bayesian Information Criterion [aBIC], Bootstrapped Likelihood Ratio Test [BLRT], parsimony, and interpretability). An overview of criteria used to select the optimal number of trajectory classes is provided in Table 3. These results show aBIC to decrease across iterations, however, BLRT suggests a 4-class solution offers the optimal fit. Further, examination of the 5-class model reveals two classes that comprise less than 5% of the sample (class 3 n = 11 [\< 1%]; class 4 n = 63 [3%]). Therefore, based on substantive interpretation, parsimony, and fit, we opt to select the four-class model of BPM Externalizing scores as providing the best overall solution. Estimated model parameters are presented in Table 4. Kenny's comment regarding previous sentence: This is one of those areas where some might argue there are too many investigator degrees of freedom. I also wonder whether there should be discussion of other issues like factor mixture models. nonlinear 

results show a small (n = 64; 4%) group of youth with a persistently high BPM Externalizing trajectory and large group of youth (n = 1437; 77%) following a low and decreasing trajectory. The remaining two classes were characterized by youth with moderate initial scores that decreased across assessments (n = 191; 10%) and youth with moderate scores that remained stable over time (n = 171; 9%) (see Figure 2). Kenny's comment: I don't see "figure 2" here. Also, I might label groups as "Moderate-High decreasing and Moderate -Low Stable. I say there because the intercept mean between the two"moderates" is larget than between Moderate Decreasing and Persistent High and between Moderate Stable and Low decreasing.