# LCM-SR {.unnumbered}

#### Latent Curve Models with Structural Residuals (LCM-SR)

multivariate Latent Curve Model with Structured Residuals (LCM-SR; Curran et al., 2014) (see Figure 1). The LCM-SR model is a novel methodology that extends current analytic procedures by allowing more precise investigation into estimates of person- specific, "between-person" and time-specific, "within-person" processes among distinct constructs over time (Curran et al., 2014). This model has the ability to simultaneously estimate the association between psychopathic features and alcohol use across development, while also isolating the between-person and within-person components of these processes over time (see Curran et al., 2014). The multivariate LCM-SR has similarities to other models that have also extended the more general latent curve model (LCM) framework, such as autoregressive latent trajectory (ALT; Curran & Bollen, 2001; Bollen & Curran, 2004) models. However, unlike previous methods, a major advantage of the LCM-SR framework is that it imposes a structure onto the time- specific residuals of the observed repeated measures for each process (e.g., psychopathic features and alcohol use). This structure results in these residuals being conceptualized as time-specific estimates of the deviation between the observed repeated measure and the underlying latent growth curve. This time-specific residual structure represents the within- person portion of the model (Curran et al., 2014). It is possible to incorporate both autoregressive and cross-lagged regressions in this within-person portion of the model,

LCM-SR models require a model building process that is carried out in a series of steps (Curran et al., 2014). More simple models are specified initially such as evaluating the fit of separate univariate growth models for each process (i.e., psychopathic features, alcohol use). Subsequent models increase in complexity and the ability of this added complexity to improve the model is evaluated at each step by examining the results Satorra-Bentler chi- square difference testing (Satorra & Bentler, 2001), as well as evaluation of additional fit indices (e.g., CFI, RMSEA, BIC, Wald tests).

In the current study, after finding each of our univariate growth curve models to provide a good fit to the data, our first step was to combine the trajectories of psychopathic features and alcohol use into a parallel process Latent Growth Curve Model (LGCM). Next we imposed a structure onto the time-specific residuals and specified a model consisting of autoregressive and cross-lagged parameters of this residual structure. In the subsequent step the full LCM-SR model was specified by combining the parallel process LGCM with the autoregressive and cross-lagged residual structure. Finally, we compared the fit of a series of models resulting from fixing and freeing parameters of the trajectory portion of the model (i.e., slope variance for alcohol use and psychopathic features) and the residual structure aspect of the model (i.e., concurrent time-specific correlations, autoregressions, and crosslags). All models were specified using maximum likelihood estimation with standard errors and a chi-square statistic that are robust to nonnormality (MLR) in Mplus 7 (Muthén & Muthén, 1998--2012) (also see Bollen & Curran, 2004, 2006; Curran et al., 2014; Morin, Maiano, Marsh, Janosz, and Nagengast, 2011).