# Latent Growth Curves

### Latent growth curve modeling (LGCM)
LGM is a flexible modeling strategy that encompasses a set of statistical methods that allow for specifying and evaluating relationships among variables that have been assessed repeatedly across multiple measurement occasions (Preacher, et al. 2008). In its most basic form, LGM parameterizes a series of observations using two parameters, an intercept (often but not always the first observations of the series) and a slope. Each parameter has its own variance so that individual differences in level (at the point of the intercept) and rate of change (i.e., the slope) are captured. The LGM framework offers several noteworthy benefits compared to some other approaches common to longitudinal data analysis. For example, research focused on characterizing stability often resolves rank-order stability but doesn't consider mean level change. This more traditional analytic approach investigates between-individual or "rank-order" change by focusing on an individual's relative placement in a group across time (Hawes et al, 2018). While evaluating of rank-order stability can certainly offer useful insight, this approach provides little information regarding within-individual change (i.e., individual differences in slope). Additionally, LGM models are extremely flexible and can model both linear and a wide range of nonlinear slopes including slopes that follow polynomial trends, a discrete change in linear slope that occurs at a given point in time (e.g., spline), or can be relatively "free" and be fitted to model the observed variables as they appear. Note that, solely focusing on rank-order estimates can lead to fundamental misinterpretations such as concluding that a construct of interest is undergoing no substantial or meaningful change. For example, consider child A who takes part in a study and reports decreasing scores on a measure of anxiety across 4 measurement occasions. Now consider a hypothetical wherein all other youth taking part in the study exhibit similar decreases to their anxiety scores. In this instance, child A's "rank-order" in the group may not change. This would result in relatively high stability estimates despite notable within-individual change to child A's anxiety scores over time. The LGM framework effectively deals with this issue by allowing for an examination of both, intraindividual (within-person) change over time as well as interindividual (between-person) variability in these patterns of change. For many research questions, it is important to be able to resolve both normative change and variation in how individuals partake in that change. The implementation of an LGM framework can provide novel insight into continuity and change underlying phenomena of interest. A fundamental aspect of this approach is the ability to characterize the direction and rate of change at both, the group- and individual-level within a single model. In a conventional LGM a single trajectory that represents the overall group-mean is estimated, as well the individual variability around this mean trajectory. Further, extensions to the conventional LGM enable researchers to test more elaborate models. For example, theoretical accounts often hypothesize that different unobserved subpopulations of individuals in a population exhibit unique patterns of growth across development. More advanced LGM methods, including latent class growth analysis (LCGA) and growth mixture modeling (GMM), accommodate this increased complexity by estimating distinct trajectories that can differ in their direction and rate of change Kenny's comment: Add citation. In addition to modeling growth, LGM methods allow researchers to evaluate other substantive questions relevant to continuity and change, such as the influence of time-varying covariates, antecedent predictors and consequences of change, and unidirectional and transactional processes among multiple growth processes. To better demonstrate applications and advantages of the LGM framework we now turn to several worked examples using real-world data from the ABCD Study Curated Annual Release 2.0 (MPlus and R code for all examples is provided in supplemental documents). Example data come from the youth self-report version of the Brief Problem Monitor (BPM; citation). The BPM is a rating instrument used to monitor children's functioning and response to interventions. The measure includes 18-items scored on a 0 ("not true") to 2 ("very true") scale and is comprised of 3 subscales (Externalizing, Internalizing, Attention). BPM data used in the following examples was collected across 3 measurement occasions (i.e., 6-month, 1-year, and 18-month follow-up assessments) and only youth with complete BPM data at each assessment Kenny's comment: I might say, for purposes of illustrations as we don't want to encourage folks to routinely use listwise deletion were included in the worked examples (n = 1,864). All models were estimated using maximum likelihood estimation with robust standard errors (MLR). Model fit was assessed using several common fit indices (e.g., Comparative Fit Index [CFI; Hu & Bentler, 1999], Root Mean Square Error of Approximation [RMSEA; Browne, Cudeck, Bollen, & Long, 1993], sample-size adjusted Bayesian Information Criterion [BIC]. Example 1. The Conventional Latent Growth Model (LGM) A conventional LGM consists of repeated measurements of some variable 'y'. In this model two latent factors are specified to represent facets of change in y over time. The first latent factor, the intercept, represents y at baseline or when the time variable is equal to 0 (t = 0). The second latent factor, the slope, represents linear change in y across the repeated measurements. In a conventional LGM the following six parameters are estimated: 1) intercept mean (μi); 2) intercept variance (θi); 3) slope mean (μs); 4) slope variance (θs); 5) intercept and slope covariance (θis); and 6) an error variance that remains constant across repeated measurements (θε). We will now evaluate a conventional LGM that was estimated using BPM Externalizing scale scores obtained across 3 measurement occasions. An examination of the Comparative Fit Index (CFI) and root mean square error of approximation (RMSEA) reveals evidence of poor model fit (CFI = .91; RMSEA = .25). Although CFI was within the generally acceptable range (i.e., \>.90; citation), RMSEA was well above the generally recommended minimum cutoff (i.e., \<.10; citation). This suggests it is necessary to reevaluate our specified model. In the context of the current example however, we shall proceed as though the model demonstrated adequate fit. Observing the model parameter estimates shows the mean estimated intercept (μ = 1.86, SE = 0.04) and linear slope (μ = -.09, SE = 0.02) to be significant (ps \< .001). While the intercept factor provides information about initial status, some researchers suggest that this parameter is primarily meaningful for growth processes with a natural origin (Stoel, 2003; Stoel & van den Wittenboer, 2003). For the conventional LGM, the parameter that is most often of central interest is the slope factor. In the present example, the negative linear slope value indicates that there is a systematic mean-level decrease in BPM Externalizing scores across assessment waves (see Figure 1a). Importantly however, the variance estimate around this group-mean trajectory is statistically significant (θs = .38, p \< .001). This indicates that although BPM Externalizing scores are decreasing on average, there is significant within-individual variability in these patterns of change (see Figure 1b).