# Difference Scores

## Overview
Difference scores are one of the earliest developed and most commonly used approaches for analyzing data collected across multiple measurement occasions[@castro-schilo2018; @jennings2016]. This approach computes a raw difference score as an index change in relation to some variable by subtracting the variable's value obtained at a prior measurement occasion from the value of the same variable obtained at a subsequent  occasion. This difference value is then be used as the outcome in a GLM to test for differences in the amount of change over time and between groups of interest.

::: {.panel-tabset}

# Model Assumptions
test test

<!-- NOTES
approach- each method is presented according to the following triplet: 
(1) when to apply it and what is it doing
(2) how to compute it in R 
(3) how to present, visualize, and interpret the results
-->

# Notes_TBD
Since the data being compared at exactly two points in time is paired (non-independent), the paired t-test analysis is appropriate. With the exception of this aspect of (non)independence in paired, longitudinal data, the underlying assumptions for this type of analysis are exactly the same as for the independent samples t-test:

non-independence means that a portion of the variance in the data is due to the individual differences that existed at the first point in time, not due to intervention-caused differences across the two points in time

Type of (Outcome) Variable: The scale of measurement for the dependent variable is continuous (interval).
Normal Distribution: The dependent variable is normally distributed in the population, or a sufficiently large sample size was drawn to allow approximation of the normal distribution. Note: the “rule of thumb” is that neither group should be smaller than 6, and ideally has more.
Independent Observations: Individuals within each sample and between the two groups are independent of each other—random selection indicates that the chances of any one “unit” being sampled are independent of the chances for any other being sampled.
Homogeneity of Variance: Variance is the same for the two groups, as indicated by equal standard deviations in the two samples.

:::

<div class="bd-callout bd-callout-info">
<h3 id="dealing-with-specificity", style="color:light"> test </h3>

> !Important Note.
>These models (t-test, ANOVA, and regression) are equivalent and all are subsumed by the GLM framework. More specifically, ANOVA is a special case of regression analysis where all the predictor variables are categorical. For the two-group case, the ANOVA model can be written as the following regression model $x_{t2}$ - $x_{t1}$=$β_0$ + $β_1$ *C* + $\epsilon$ ($x_{t2}$ - $x_{t1}$) where $x_{t2}$ - $x_{t1}$ is the difference between Time 2 ($_{t2}$) and Time 1 ($_{t1}$) scores, $β_0$  is the intercept or average predicted value of the difference across time for individuals in group = 0, ''$β_1$' is the regression coefficient for *C* indicating the difference in difference scores between between group = 0 and group = 1, and $\epsilon$($x_{t2}$ - $x_{t1}$) is the residual (i.e., error) score (normally distributed with zero mean) that captures all other factors not accounted for by the grouping predictor. Typically, the effect of interest is "$β_1$", which represents the difference between the average difference scores of the two groups. 
___

>**Key Considerations & Limitations**
>+ Imbalanced baseline scores
>	+ If baseline scores are imbalanced across groups, effect estimates of the mean difference score may become biased (via regression to the mean). This can lead individual studies to produce different conclusions regarding equivalent models.
>+ Reliability and Stability
>	+ Increased stability (over time) can lead to decreased reliability of difference scores. That is, the stronger the Time 1–Time 2 correlation, the less variability in the difference score there is to detect (can't predict/detect what's not there).
		+ See Cronbach and Furby (1970)[@cronbach1970]; but also Jennings & Cribbie, 2016[@jennings2016]; Rogosa, Brandt, & Zimowski, 1982[@rogosa1982]; Wright, 2006[@wright2006]
	+ Raw Scores
		+ Prestandardizing variables discards important variance information and as such, raw scores should be used when computing difference scores 
	+ Types of change
	+ A concern more broadly with studies that include only two measurement occasions is that only rank-order changes in levels of a variable can be measured [@king2018]. 

## Explanation

##### Difference Scores
In a repeated measures design, a difference score $(\Delta)$ can be calculated by subtracting pairs of values on some variable ($x$) produced by the same individual across two (or more) timepoints $(x_{t1}, x_{t2})$. First, compute the difference ($\Delta$) between the score ($x$) obtained at baseline ($x_{t1}$) and follow-up ($x_{t2}$) for each individual ($(\Delta = x_{t2} − x_{t1})$). This difference value ($\Delta$ = $x_{t2}$ - $x_{t1}$) can then be used as the outcome in a GLM to test for differences in the amount of change over time and between groups of interest. 

#### **Single-Group Repeated Measures Design:** {#sec-equation}
The most basic repeated measures design the involves a single-group repeated measures design. In this design, we have n repeated measures of the response on each of N subjects.

##### (Paired Samples T-test)
The paired samples t-test can be used to determine whether the difference between some pair of values produced by the same individual across two measurement occasions, differs significantly from 0. The t-testp is a special case of the one-sample t-test, with the exception that this model needs to be modified to account for the statistical dependence among repeated observations obtained on the same subject, other than the issue of non-independence the underlying assumptions for the t-testp is exactly the same as for the independent samples t-test. 

To compute the t-testp ($(\Delta = x_{t2} − x_{t1})$) the *sample average of differences* value obtained from the formula provided in step 1 ($(\Delta = x_{t2} − x_{t1})$) will be used as the numerator in your calculation of the t-value. The denominator in this computation is a variance estimate (i.e., the sample standard error), which accounts for the covariance between initial levels and change. A significant t-statistic indicates that change $(\Delta)$ from T1 to T2 is significantly greater than 0.

> Hypothetical Scenario:
Table 1. Raw and difference scores before and after training.

Table 1 shows scores on a quiz that five employees received before they took a training course and after they took the course. The difference between these scores (i.e. the score after minus the score before) represents improvement in the employees’ ability. This third column is what we look at when assessing whether or not our training was effective. We want to see positive scores, which indicate that the employees’ performance went up. 

##### (rANOVA)
The repeated-measures (within-subjects) ANOVA is an extension of the paired-samples t-test that is used to determine whether mean scores on some outcome measured at three or more occasions differs significantly across measurement occasions. 

#### **Basic T-testp/ANOVA:**
can be extended for multiple groups and 3+ timepoints
1) **T-test**/**ANOVA**:
+ A t-test can be performed using a grouping variable to examine whether the disparity in the mean difference value differs significantly between two groups. An ANOVA can be used if the grouping variable includes more than 2 groups.

The basic one-way repeated measure ANOVA can be extended (e.g., two-way, three-way) to evaluate whether or not a significant interaction effect exists between two or more factors (groups/levels) of some within-subjects variable.

	+ Example based on hypothetical 
		+ First we compute the difference ($\Delta$) between the score on the measure of screen time ($x$) assessed at baseline ($x_{t1}$) and follow-up ($x_{t2}$). 
		+ The result of this formula ($\Delta$=$x_{t2}$ - $x_{t1}$) can then be used as an outcome to test the effect of group on  the difference score ($\Delta_{boys}$,  $\Delta_{girls}$ ). 
		+ Figure x.

>GLM Equation:
$RS{_n}{_2} - RS{_n}{_1} = \gamma_0 + \gamma_1 Cn + e_{n(RS2-RS1)}$

where RSn2 􏰫 RSn1 is the difference between Time 2 and Time 1 scores, g0 is the intercept or average predicted value of the difference across time in relationship satis- faction for those who did not cohabit prior to marriage (Cn 1⁄4 0), g1 is the regression coefficient for Cn indicating the difference in change between Time 1 and Time 2 between those who cohabited and those who did not, and en(RS2􏰫RS1) is the residual score that captures all other factors not accounted for by the cohabited predictor. Importantly, if the key predictor, Cn, was continuous (e.g., number of months couples lived together before marriage), the model in Equation 2 would no longer be called repeated measures ANOVA, but Sofia could compute the difference score variable herself and run a simple linear regression with Cn as the sole predictor to assess whether increases in time cohabiting prior to marriage predict change in relationship satisfaction.

> Hypothetical Scenario:
> 	A study investigates sex differences on a measure of screen time by examining change in screen time scores obtained across two measurement occasions for boys and girls. The study aims to determine whether sex has an effect on changes in screen time across assessments.

#### **Basic Regression:**
2) **Regression**:
+  A simple regression analysis can be performed using a grouping variable as a predictor of change ($\Delta$) in an outcome across groups. A significant effect for the grouping variable indicates that average $\Delta$ is significantly different across groups.
	+ Example based on hypothetical
		+ First we compute the difference ($\Delta$) between the score on the measure of screen time ($x$) assessed at baseline ($x_{t1}$) and follow-up ($x_{t2}$). 
		+ The result of this formula ($\Delta$=$x_{t2}$ - $x_{t1}$) can be included as the outcome variable in a regression model that analyzes the role of the grouping variable (0 = boy; 1 = girl) on changes in screen time across measurement occassions.
	+ Figure x.
:::

## Explanation of Model Code & Plots
### Model code

