# 17. RI-CLPM

Fortunately, there exists a range of models that have been proposed to distinguish between- and within-person relations across time [see @littlefield2021; @orth2021]. Most of these alternative models stem from latent state-trait models [@schmitt1993], where a latent variable (typically referred to as a "trait) captures between-person sources of variance and covariance among a series of repeated assessments across time. After accounting for this source of variance, relations among specific assessments across time (e.g., the relation between Construct 1 at Time 1 with Construct 2 at Time 2) can be modeled akin to the CLPM that are thought to capture "state" relations. More contemporary models, such as the Random-Intercept Cross-Lagged Panel Model [RI-CLPM; @hamaker2015] and the Latent Curve with Structured Residuals [LCM-SR; @curran2014a] utilize structured residuals, or time-specific latent variables that capture within-person deviations around an individual's mean (or trait) level across time. For example, when a random intercept (i.e., within a SEM framework, a latent variable where each assessment serves as an indicator and all factor loadings are constrained to unity) is added to a series of repeated assessments, the estimated score for a given individual at a given timepoint becomes a function of: 1) the mean at a given timeframe and 2) the latent variable score for a given individual. Any difference, or residual, between the actual scores and estimated score for a given individual at a given point of assessment can be thought of as within-person variance at that timepoint, and this within-person variance is captured by the structured residual [see @littlefield2021, for an example with actual data]. The RI-CLPM proposed by @hamaker2015] only includes a random intercept, whereas the LCM-SR proposed by @curran2014a also includes additional growth factors, such as a random linear slope (such that the LCM-SR could be considered as a hybrid between traditional latent growth modeling with autoregressive and cross-lagged relations among structured residuals). Variants of these models [see @littlefield2021, for more details], such as relaxing the assumption of unit factor loadings inherent in a random-intercept model, can also be estimated given an adequate number of assessments (typically four or more) are acquired [see @mulder2021 & @hamaker2020a for a description and @littlefield2021, for a worked example of the impact of these adjustments on model estimates].

It is important to realize the various assumptions inherent in these models [see @littlefield2021, for more details]. For example, a random-intercept only model assumes equivalent covariances among repeated assessments (as does compound symmetry described above), and the only way to relax this assumption is through the inclusion of relations among the structured residuals. Indeed, when the assumption of covariance stationarity holds (i.e., the assumption inherent in the oft-used repeated measures ANOVA), all the relations among the structured residuals become zero [see @littlefield2021, for a demonstration]. Conversely, the LCM-SR can relax the assumption of stationarity of covariances by the inclusion of additional growth factors (e.g., a random linear slope) in addition to the relations among structured residuals. Thus, as demonstrated in @littlefield2021, different relations among variables thought to capture within-person sources of variance can be obtained in the same data depending on the choice of growth factors (i.e., intercept-only vs. models that include additional growth factors) and if mean structure is also considered [see @littlefield2021]. Evidence also suggests that achieving model convergence is more difficult for some models (e.g., the LCM-SR) compared to other models (e.g., the RI-CLPM; see @orth2020) when modeling is based on default specifications. In sum, the importance of isolating the appropriate level of analysis in prospective data has been stressed by several researchers (particularly among Patrick Curran and colleagues within SEM frameworks). Despite this, models such as the CLPM remain common within various extant literatures. There are multiple alternatives that have been recommended, though these models require multiple assessments waves (e.g., four or more to fully specify the LCM-SR), additional expertise to overcome issues with model convergence, and appreciation of modeling assumptions when attempting to adjudicate among potential models in each research context [see @littlefield2021, for further discussion].


### Autoregressive and cross-lagged panel analysis (ARCL)

Rank-order stability can be used to model interindividual stability over time as an autoregressive process,. That is, the rank-order stability can be used to model continuity of a behavior. Assuming equal intervals, the correlations between T0 and T1, and between T1 and T2 could be used to estimate the correlation between T2 and T3.

Multilevel modeling approaches have often stressed methods to tease apart different sources of variance [e.g., distinguishing level-1, or within-person, variables from level-2, or between-person, variables in the context of prospective data; see @raudenbush2002]. However, models common in SEM, such as the CLPM, have been criticized extensively on the grounds this modeling approach cannot delineate between- and within-person sources of variation and covariations [see @littlefield2021, for a review]. Briefly, the CLPM assumes no stable between-person differences (beyond the implied relations among the auto-regressive paths) among the constructs that are assessed repeated ly. As noted by @hamaker2015, "...if stability of the constructs is to some extent of a trait-like, time-invariant nature, the inclusion of autoregressive parameters will fail to adequately control for this. As a result, the estimates of the cross-lagged regression coefficients will be biased, which may lead to erroneous conclusions regarding the underlying causal pattern." (p. 10 2). As demonstrated by @littlefield2021, the CLPM assumes relations identical to a series of two-predictor regression models in terms of estimating variances and covariances among measurements across ti me. As described above, regression models based on two waves of assessment are limited on several fronts, including being able to tease apart between- and within-person sources of variance. @hoffman2015 notes the cross-lagged estimate "smushes" the between- and within-person effects together as a single estima te. @berry2017a notes this results in CLPM estimates "...that are difficult (or impossible) to interpret meaningfully." (p. 118 7). Given these observations, and that prospective data are often used to inform theories involving clear within-person processes [e.g., see @curran2011], models that more optimally delineate between- and within-person sources of variance are need ed.

## What it is and when to use it

The cross lagged panel model (CLPM) is a flexible analytic approach that is commonly applied when researchers are interested in understanding how variables influence each other over time. This framework requires at least two variables assessed across two measurement occassions. Consider the most basic -- and eponymously named-- CLPM, which models the lagged associations between two variables (x, y). Let 'x1' and 'y1' denote variables x and y at time 1 and allow 'x2' and 'y2' denote variables x and y at time 2. This model compares the relative effects of x and y on each other ('x1-\>y2', 'y1-\>x2') (see Figure x) and can be easily extended to evaluate other hypothesized relationships. For example, evaluating contemporaneous associations between variables assessed during the same measurement occassion (e.g., 'x1 \<-\> y1'; 'x2 \<-\> y2'; see Figure x) is straightforward. Another common CLPM extension is the inclusion of autoregressive effects (e.g., 'x1-\>x2', 'y1-\>y2'; see Figure x). Also referred to as an autoregressive cross-lagged [ARCL] model, this extension provides an estimate of a variable's temporal (i.e., rank order) stability over time. The larger the value of the autoregressive coefficient (closer to 1) the more stable (greater % of variance explained in) the variable across measurement occasions. When contemporaneous (e.g., x1 \<-\> y1) and autoregressive effects (e.g., x1 -\> x2) are included, the standardized cross-lagged parameters of an ARCL model are often inferred as representing the bidirectional 'between-person' effects of 'x1-\>y2' (when controlling for y1) and 'y1-\>x2' (when controlling for x1).

One advantage of longitudinal analyses with multiple waves of data collection is that such processes can be modeled over time. Understanding transactional effects effects can be useful in devising strategies to intervene in various types of escalating cycles of violence such as child maltreatment [@cicchetti2006a) or the effects of intimate partner violence on child behavior problems [@chung2021]. Such processes could be modeled statistically in a number of ways by relying on estimating cross-lagged relations but require at least three times of measurement in order to distinguish beween-subject and within-sources of measurement [@hamaker2015; see discussion below).