# ex1.ancova {.unnumbered}

```{r}
#| include: FALSE
#Preliminary Setup
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#| class.source: 'fold-hide'
#| message: FALSE
#| warning: FALSE
#| echo: FALSE

# Install necessary packages (if not already installed)
if (!("rstatix" %in% installed.packages())) install.packages("rstatix")
if (!("lme4" %in% installed.packages())) install.packages("lme4")
if (!("lmerTest" %in% installed.packages())) install.packages("lmerTest")
if (!("tidyverse" %in% installed.packages())) install.packages("tidyverse")
if (!("ggpubr" %in% installed.packages())) install.packages("ggpubr")
if (!("emmeans" %in% installed.packages())) install.packages("emmeans")
```

```{r}
#| class.source: 'fold-hide'
#| message: FALSE
#| warning: FALSE
#| echo: FALSE

#Load packages
library(rstatix)
library(lme4)
library(lmerTest)
library(tidyverse)
library(ggpubr)
library(emmeans)
```

```{r}

df_wide<- read_csv("/Users/shawes/Desktop/df_wide.csv")

df_wide %>%
            group_by(Sex) %>%  
            summarise(mean_grade = mean(Externalizing_T0),
            sd_grade = sd(Externalizing_T0),
            mean_exam = mean(Externalizing_T1),
            sd_exam = sd(Externalizing_T1))

# Boxplot of CBCL Externalizing scores at baseline by sex
boxplot_cbclExt_T1 <- boxplot(Externalizing_T0 ~ Sex,data = df_wide,
main = "CBCL Ext Baseline Score by sex",
xlab = "Sex",ylab = "Baseline CBCL Externalizing Score",
col = "red",border = "black")

# Boxplot of CBCL Externalizing scores at 1-Year follow-up by sex
boxplot_cbclExt_T2 <- boxplot(Externalizing_T1 ~ Sex, data = df_wide,
main = "CBCL Ext 1-Year Follow-up Score by sex",
xlab = "Sex",ylab = "1-Year Follow-up CBCL Externalizing Score",
col = "red",border = "black")

suppressWarnings(print(boxplot_cbclExt_T1))
suppressWarnings(print(boxplot_cbclExt_T2))

```

```{r}

#An ANCOVA approach can be used to examine effects of a categorical covariate when controlling for autoregressive effects (t1->t2)

#Fit ANCOVA Model
ancova_result <- aov(Externalizing_T1 ~ Sex + Externalizing_T0, data = df_wide)
Anova(ancova_result, type="III")

#Diagnostic Plots
# residuals vs. fitted values plot.
resid_plot<- plot(ancova_result, add.smooth = FALSE, which = 1)

# normal probability plot
norm_plot<- plot(ancova_result, which = 2)

# scale location plot
scale_plot<- plot(ancova_result, add.smooth = FALSE, which = 3)

# boxplot
boxplot <- ggplot(df_wide, aes(x = Externalizing_T1, y = Externalizing_T0, colour = Sex)) + geom_point()

suppressWarnings(print(resid_plot))
suppressWarnings(print(norm_plot))
suppressWarnings(print(scale_plot))
suppressWarnings(print(boxplot))
```

```{r}

#Post-hoc test
# Pairwise comparisons
pwc <- df_wide %>% 
  emmeans_test(
    Externalizing_T1 ~ Sex, covariate = Externalizing_T0,
    p.adjust.method = "bonferroni"
    )
pwc

# Display the adjusted means of each group (i.e., estimated marginal means)
get_emmeans(pwc)

# Visualization: line plots with p-values
pwc <- pwc %>% add_xy_position(x = "Sex", fun = "mean_se")
ggline(get_emmeans(pwc), x = "Sex", y = "emmean") +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) + 
  stat_pvalue_manual(pwc, hide.ns = TRUE, tip.length = FALSE) #+
# labs(
#    subtitle = get_test_label(pwc, detailed = TRUE),
#    caption = get_pwc_label(pwc)
#  )
```
